// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prueba_tecnica_finixgroup.Helpers;

#nullable disable

namespace prueba_tecnica_finixgroup.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240314155059_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("prueba_tecnica_finixgroup.Server.Models.Bank", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IBAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("account_number")
                        .HasColumnType("TEXT");

                    b.Property<string>("bank_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("routing_number")
                        .HasColumnType("TEXT");

                    b.Property<string>("swift_bic")
                        .HasColumnType("TEXT");

                    b.Property<string>("uid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("lower(hex(randomblob(16)))");

                    b.HasKey("id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            id = 3282,
                            account_number = "0472524631",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "693911739",
                            swift_bic = "MORLGB2LSMK",
                            uid = "4298afbc-8aaa-4ce7-9445-443c931af29b"
                        },
                        new
                        {
                            id = 3802,
                            account_number = "6071659669",
                            bank_name = "ABINGWORTH MANAGEMENT LIMITED",
                            routing_number = "078363067",
                            swift_bic = "ABBEGB21",
                            uid = "8e14b0e3-28f7-4fa0-b809-6b5a21e90831"
                        },
                        new
                        {
                            id = 621,
                            account_number = "0906354893",
                            bank_name = "ABINGWORTH MANAGEMENT LIMITED",
                            routing_number = "323840002",
                            swift_bic = "BOFAGB3SSWI",
                            uid = "090cef25-39d4-4e73-87bc-df7c5dc7dc89"
                        },
                        new
                        {
                            id = 3800,
                            account_number = "0794435344",
                            bank_name = "THE ROYAL BANK OF SCOTLAND PLC (FORMER RBS NV)",
                            routing_number = "227298789",
                            swift_bic = "BKCHGB2UXXX",
                            uid = "04ef45b3-6463-4765-9249-391eb7864d2d"
                        },
                        new
                        {
                            id = 9719,
                            account_number = "7009390273",
                            bank_name = "ABN AMRO HOARE GOVETT CORPORATE FINANCE LTD.",
                            routing_number = "643115200",
                            swift_bic = "BOFAGB22CLS",
                            uid = "0152d7a0-6bd7-47fb-9d52-061a675b4849"
                        },
                        new
                        {
                            id = 5722,
                            account_number = "9324571965",
                            bank_name = "SANTANDER UK PLC",
                            routing_number = "013618861",
                            swift_bic = "AAFMGB21",
                            uid = "bc668ddd-7e85-4008-b34a-d4240d7417a2"
                        },
                        new
                        {
                            id = 5983,
                            account_number = "2096461884",
                            bank_name = "ABU DHABI ISLAMIC BANK",
                            routing_number = "219073912",
                            swift_bic = "AACCGB21",
                            uid = "e51df290-e837-4225-8b0f-31955120f816"
                        },
                        new
                        {
                            id = 9052,
                            account_number = "5598352160",
                            bank_name = "ABBEY LIFE",
                            routing_number = "291144830",
                            swift_bic = "ANTSGB2LCHA",
                            uid = "bd244a46-ce75-4986-b43f-08231a4ddc27"
                        },
                        new
                        {
                            id = 8340,
                            account_number = "1801484613",
                            bank_name = "ABG SUNDAL COLLIER LIMITED",
                            routing_number = "121323653",
                            swift_bic = "ABAZGB21",
                            uid = "ab54e2b9-eec0-4382-9aac-ab25e396f1ae"
                        },
                        new
                        {
                            id = 6469,
                            account_number = "2587601314",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "062731304",
                            swift_bic = "ABFIGB21",
                            uid = "0809e1c3-b3d3-4ad1-b45c-a33835ff2815"
                        },
                        new
                        {
                            id = 6983,
                            account_number = "9528777042",
                            bank_name = "ABINGWORTH MANAGEMENT LIMITED",
                            routing_number = "106080746",
                            swift_bic = "BARBGB2LBIR",
                            uid = "5339146d-5fb1-4ced-a95d-2612e4efc702"
                        },
                        new
                        {
                            id = 7052,
                            account_number = "1712915723",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "674404029",
                            swift_bic = "ABCCGB22",
                            uid = "c7daa704-d455-479d-b3a8-8f56e237a2ff"
                        },
                        new
                        {
                            id = 3220,
                            account_number = "1007622495",
                            bank_name = "OTKRITIE SECURITIES LIMITED",
                            routing_number = "632641442",
                            swift_bic = "ABNAGB21VOC",
                            uid = "c48373b5-b1f3-423c-a0c4-6eddcb014cf3"
                        },
                        new
                        {
                            id = 5430,
                            account_number = "6616185510",
                            bank_name = "ABBEY LIFE",
                            routing_number = "324871656",
                            swift_bic = "BCYPGB2LBBB",
                            uid = "425f1441-17d1-4570-b55f-bd875188e256"
                        },
                        new
                        {
                            id = 2149,
                            account_number = "0167111793",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "235725008",
                            swift_bic = "ABAZGB21",
                            uid = "1f141bea-6cb8-43fa-a8ef-85b7e38af14d"
                        },
                        new
                        {
                            id = 5656,
                            account_number = "7768934454",
                            bank_name = "ABN AMRO HOARE GOVETT CORPORATE FINANCE LTD.",
                            routing_number = "069293968",
                            swift_bic = "AAFMGB21",
                            uid = "237cc7f4-3e31-4da8-9cab-3f64f7cc57e5"
                        },
                        new
                        {
                            id = 3077,
                            account_number = "1177210059",
                            bank_name = "ABBEY LIFE",
                            routing_number = "103259583",
                            swift_bic = "AAFMGB21",
                            uid = "ce40343d-eb88-40c4-9e37-947780666007"
                        },
                        new
                        {
                            id = 4358,
                            account_number = "7827887923",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "276584855",
                            swift_bic = "BCYPGB2LSSB",
                            uid = "a2160a7f-95df-4436-99f5-d55a8548a0ab"
                        },
                        new
                        {
                            id = 1315,
                            account_number = "0828824404",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "049830215",
                            swift_bic = "ABCMGB21",
                            uid = "b3a29564-dfb2-483c-9f04-7fbf89ffb54d"
                        },
                        new
                        {
                            id = 9036,
                            account_number = "4415135339",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "277623317",
                            swift_bic = "AAHVGB21",
                            uid = "7dda5625-ebf5-40ae-82fe-ed37b931e0fc"
                        },
                        new
                        {
                            id = 2040,
                            account_number = "7978914690",
                            bank_name = "ABN AMRO HOARE GOVETT LIMITED",
                            routing_number = "614897162",
                            swift_bic = "UBKLGB2LBAK",
                            uid = "baea4835-a647-4eaa-b60f-70596579ade9"
                        },
                        new
                        {
                            id = 1159,
                            account_number = "9075948519",
                            bank_name = "ABN AMRO FUND MANAGERS LIMITED",
                            routing_number = "328674671",
                            swift_bic = "BOFAGB3SSWI",
                            uid = "c78b1dd3-2f03-4f0a-a4a6-6a2c43c5613a"
                        },
                        new
                        {
                            id = 6440,
                            account_number = "3249515617",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "287170892",
                            swift_bic = "BCYPGB2LPGB",
                            uid = "fad1ccdf-6179-495c-b894-561d85ba039b"
                        },
                        new
                        {
                            id = 8391,
                            account_number = "7715244346",
                            bank_name = "OTKRITIE SECURITIES LIMITED",
                            routing_number = "326946929",
                            swift_bic = "BCEYGB2LXXX",
                            uid = "5c5dcde4-3b0f-422b-9407-3017b721e9a3"
                        },
                        new
                        {
                            id = 2515,
                            account_number = "1620392290",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "128348398",
                            swift_bic = "BOFAGB4TLFS",
                            uid = "f2c25cc6-1802-4d57-a86b-e0f52cbfdb52"
                        },
                        new
                        {
                            id = 8822,
                            account_number = "8666970108",
                            bank_name = "THE ROYAL BANK OF SCOTLAND PLC (FORMER RBS NV)",
                            routing_number = "803545445",
                            swift_bic = "ABCMGB21",
                            uid = "ee0285d2-29ce-49d2-80d0-43a0f0994f52"
                        },
                        new
                        {
                            id = 3389,
                            account_number = "6435814142",
                            bank_name = "ABN AMRO HOARE GOVETT CORPORATE FINANCE LTD.",
                            routing_number = "240168922",
                            swift_bic = "BKCHGB2LXXX",
                            uid = "2df76a3e-24f1-4e3e-85b5-7ce2cea191f9"
                        },
                        new
                        {
                            id = 244,
                            account_number = "3258937445",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "234043176",
                            swift_bic = "BARBGB2LTOO",
                            uid = "0dce483a-a3df-401c-be23-a8ead87a977f"
                        },
                        new
                        {
                            id = 4911,
                            account_number = "3038318755",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "250621048",
                            swift_bic = "BCYPGB2LBBB",
                            uid = "e2588ef1-5beb-4ac7-bb9b-8fe4ee5d3dd3"
                        },
                        new
                        {
                            id = 3121,
                            account_number = "8799350402",
                            bank_name = "OTKRITIE SECURITIES LIMITED",
                            routing_number = "232054730",
                            swift_bic = "BCYPGB2LMBB",
                            uid = "2cddae93-abcb-44f6-9799-8bd8b107278f"
                        },
                        new
                        {
                            id = 6087,
                            account_number = "8040510153",
                            bank_name = "ABN AMRO CORPORATE FINANCE LIMITED",
                            routing_number = "685702561",
                            swift_bic = "BOFAGB4TLTR",
                            uid = "f3dd32fa-d685-4c18-b4f8-9d80643a8f5f"
                        },
                        new
                        {
                            id = 3756,
                            account_number = "2378527930",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "241811757",
                            swift_bic = "UBKLGB2LBAK",
                            uid = "98688059-8fe9-4c52-8b9e-3484b69e837b"
                        },
                        new
                        {
                            id = 7104,
                            account_number = "0997878822",
                            bank_name = "ABINGWORTH MANAGEMENT LIMITED",
                            routing_number = "070264627",
                            swift_bic = "BCYPGB2LBBB",
                            uid = "e2c29dc9-e00f-4fab-afbf-88da79a69ed6"
                        },
                        new
                        {
                            id = 2243,
                            account_number = "1012546588",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "315530003",
                            swift_bic = "BCYPGB2LSSB",
                            uid = "84c56d8a-8dd3-40b1-86d2-f31f421d2b49"
                        },
                        new
                        {
                            id = 3631,
                            account_number = "0072558250",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "702838237",
                            swift_bic = "BARBGB2LHAR",
                            uid = "5a09e442-c721-4967-a2f1-7d59cb3ae08a"
                        },
                        new
                        {
                            id = 5915,
                            account_number = "5328822406",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "280279923",
                            swift_bic = "BCYPGB2LCBB",
                            uid = "ed29c020-726e-4ff7-90f0-f6b3f21f1c45"
                        },
                        new
                        {
                            id = 940,
                            account_number = "6274419110",
                            bank_name = "PGMS (GLASGOW) LIMITED",
                            routing_number = "611223218",
                            swift_bic = "BOFAGB22OF2",
                            uid = "2d287a8c-54b2-4019-ab00-507119a68438"
                        },
                        new
                        {
                            id = 7697,
                            account_number = "8210385685",
                            bank_name = "THE ROYAL BANK OF SCOTLAND PLC (FORMER RBS NV)",
                            routing_number = "301059174",
                            swift_bic = "AAPUGB21",
                            uid = "aedfea8a-3b7c-4f9a-ae94-8bb8af5bb63e"
                        },
                        new
                        {
                            id = 3525,
                            account_number = "6832417509",
                            bank_name = "ABINGWORTH MANAGEMENT LIMITED",
                            routing_number = "800735274",
                            swift_bic = "BCYPGB2LPGB",
                            uid = "26470875-70b0-4ef3-bd07-57b2492115ce"
                        },
                        new
                        {
                            id = 224,
                            account_number = "8998184740",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "063659045",
                            swift_bic = "AIBKGB2XTSY",
                            uid = "8cc0a25e-29ad-41da-858a-19fa238b9bda"
                        },
                        new
                        {
                            id = 7988,
                            account_number = "4695001952",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "053067663",
                            swift_bic = "AAFMGB21",
                            uid = "849a71e6-5dd0-4ae9-ae85-507c3af2afe9"
                        },
                        new
                        {
                            id = 5476,
                            account_number = "0948977507",
                            bank_name = "ABG SUNDAL COLLIER LIMITED",
                            routing_number = "087033760",
                            swift_bic = "UBKLGB2LXXX",
                            uid = "46541c0e-a583-4d35-807e-2bf7e039b25f"
                        },
                        new
                        {
                            id = 4988,
                            account_number = "6313763236",
                            bank_name = "UBS CLEARING AND EXECUTION SERVICES LIMITED",
                            routing_number = "722517897",
                            swift_bic = "ABNAGB21VOC",
                            uid = "f040b0d8-5ff8-45c8-b130-8c4d12b57114"
                        },
                        new
                        {
                            id = 7824,
                            account_number = "2001619206",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "047648014",
                            swift_bic = "ABCEGB2L",
                            uid = "8f173a2a-0693-4199-9577-c6be8f92605c"
                        },
                        new
                        {
                            id = 4324,
                            account_number = "7895679073",
                            bank_name = "ABU DHABI ISLAMIC BANK",
                            routing_number = "069069228",
                            swift_bic = "BOFAGB22SCP",
                            uid = "ba728df8-b668-41c9-9888-c49b58638734"
                        },
                        new
                        {
                            id = 4374,
                            account_number = "5780068547",
                            bank_name = "ABN AMRO HOARE GOVETT CORPORATE FINANCE LTD.",
                            routing_number = "612711554",
                            swift_bic = "ABAZGB21",
                            uid = "f96f0127-212c-4359-ae27-bc18596bc194"
                        },
                        new
                        {
                            id = 3680,
                            account_number = "1057359365",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "104640337",
                            swift_bic = "AAPEGB21",
                            uid = "5bee8501-da0e-4dde-bdff-0576524f29aa"
                        },
                        new
                        {
                            id = 5612,
                            account_number = "8456711064",
                            bank_name = "ABU DHABI ISLAMIC BANK",
                            routing_number = "222800897",
                            swift_bic = "MORLGB2LSMK",
                            uid = "b5a4df95-2594-4cf0-88bf-1d8e81d5eb02"
                        },
                        new
                        {
                            id = 1102,
                            account_number = "2708738488",
                            bank_name = "THE ROYAL BANK OF SCOTLAND PLC (FORMER RBS NV)",
                            routing_number = "264209207",
                            swift_bic = "BOFAGB4TLTR",
                            uid = "df777d5e-f739-483d-8211-01735f98388a"
                        },
                        new
                        {
                            id = 7367,
                            account_number = "4568167857",
                            bank_name = "ABINGWORTH MANAGEMENT LIMITED",
                            routing_number = "259533522",
                            swift_bic = "AANLGB21",
                            uid = "dfbd3837-862d-4ecd-ad2a-24408aeeb7f2"
                        },
                        new
                        {
                            id = 6207,
                            account_number = "2623350128",
                            bank_name = "ABN AMRO HOARE GOVETT SECURITIES",
                            routing_number = "081291951",
                            swift_bic = "ABBEGB21",
                            uid = "94a0983f-359a-4750-94c1-458275f56b3f"
                        },
                        new
                        {
                            id = 4947,
                            account_number = "4848684424",
                            bank_name = "ABN AMRO HOARE GOVETT SECURITIES",
                            routing_number = "044065302",
                            swift_bic = "BCYPGB2LBBB",
                            uid = "52781a50-5530-4067-a7ef-e964bde5d599"
                        },
                        new
                        {
                            id = 8772,
                            account_number = "6672148490",
                            bank_name = "ABBEY LIFE",
                            routing_number = "695943462",
                            swift_bic = "AANLGB21",
                            uid = "3e521388-27ad-40a2-a75c-a4b479f757ef"
                        },
                        new
                        {
                            id = 2745,
                            account_number = "7368276432",
                            bank_name = "ABN AMRO HOARE GOVETT SECURITIES",
                            routing_number = "258466344",
                            swift_bic = "ABCCGB22",
                            uid = "a6e35170-1a58-4a37-9463-306c92d07b27"
                        },
                        new
                        {
                            id = 2418,
                            account_number = "5244753272",
                            bank_name = "ABN AMRO FUND MANAGERS LIMITED",
                            routing_number = "657074829",
                            swift_bic = "ASTPGB2LXXX",
                            uid = "c17ecad3-f372-49d9-a26a-34628653b2e7"
                        },
                        new
                        {
                            id = 5921,
                            account_number = "5884750084",
                            bank_name = "AAC CAPITAL PARTNERS LIMITED",
                            routing_number = "094421022",
                            swift_bic = "UBKLGB2LXXX",
                            uid = "b5a7ea20-a156-4d81-8dff-b6b031f63a36"
                        },
                        new
                        {
                            id = 2624,
                            account_number = "7204333852",
                            bank_name = "PGMS (GLASGOW) LIMITED",
                            routing_number = "002005540",
                            swift_bic = "AAFMGB21",
                            uid = "1c956fa5-bdd3-488e-a1b0-bcc023c3068e"
                        },
                        new
                        {
                            id = 3654,
                            account_number = "3441599921",
                            bank_name = "SANTANDER UK PLC",
                            routing_number = "321327213",
                            swift_bic = "BCYPGB2LBBB",
                            uid = "79cdf916-4873-42de-a42d-bc7fc924b7ba"
                        },
                        new
                        {
                            id = 266,
                            account_number = "6157187035",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "269868122",
                            swift_bic = "ABCMGB21",
                            uid = "fd03bac5-c799-45d1-a112-184ae7c4c596"
                        },
                        new
                        {
                            id = 8588,
                            account_number = "1239995315",
                            bank_name = "ABU DHABI ISLAMIC BANK",
                            routing_number = "110111889",
                            swift_bic = "BARBGB2LMAN",
                            uid = "f1a257c1-eeda-4128-be46-6a2017b570f3"
                        },
                        new
                        {
                            id = 6614,
                            account_number = "4808912457",
                            bank_name = "ALLIED BANK PHILIPPINES (UK) PLC",
                            routing_number = "315853298",
                            swift_bic = "BARBGB2LTOO",
                            uid = "2e3c5e3d-0607-447c-823a-81b092aeff9e"
                        },
                        new
                        {
                            id = 3567,
                            account_number = "3285585516",
                            bank_name = "ABG SUNDAL COLLIER LIMITED",
                            routing_number = "216386589",
                            swift_bic = "AAOGGB21",
                            uid = "961f425d-ab72-42cd-880b-b9bc55408d88"
                        },
                        new
                        {
                            id = 1030,
                            account_number = "4534031759",
                            bank_name = "ABU DHABI ISLAMIC BANK",
                            routing_number = "215913597",
                            swift_bic = "AIBKGB2XTSY",
                            uid = "0a6f78b9-275f-487a-b843-5ceffca35b00"
                        },
                        new
                        {
                            id = 305,
                            account_number = "3909346306",
                            bank_name = "ABC INTERNATIONAL BANK PLC",
                            routing_number = "048869300",
                            swift_bic = "BKCHGB2LXXX",
                            uid = "1b37b3d9-88a5-45c1-941f-589f47139e53"
                        },
                        new
                        {
                            id = 3104,
                            account_number = "6706920964",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "027967980",
                            swift_bic = "AACCGB21",
                            uid = "11049507-251e-43fa-9346-00a048a180f9"
                        },
                        new
                        {
                            id = 4494,
                            account_number = "2480547311",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "112333665",
                            swift_bic = "BARBGB2LMAN",
                            uid = "3b257f5f-03e6-45ea-a202-4f9302569c61"
                        },
                        new
                        {
                            id = 5284,
                            account_number = "6832738618",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "265896185",
                            swift_bic = "ABECGB21",
                            uid = "a1ebd9e3-d7c3-4d99-9201-ed1548f69014"
                        },
                        new
                        {
                            id = 5142,
                            account_number = "2926630735",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "218537187",
                            swift_bic = "BARBGB2LMAN",
                            uid = "3c864e81-7fcb-4b4e-9692-0b019ffe6665"
                        },
                        new
                        {
                            id = 5081,
                            account_number = "9860321542",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "657742012",
                            swift_bic = "BARBGB2LLEI",
                            uid = "cb8da82c-d684-4f11-9be8-dde526a2d7fe"
                        },
                        new
                        {
                            id = 3480,
                            account_number = "5704612496",
                            bank_name = "ABN AMRO FUND MANAGERS LIMITED",
                            routing_number = "028494436",
                            swift_bic = "BARBGB2LMAN",
                            uid = "2f660ba0-610d-46e8-a445-c3175071ca2a"
                        },
                        new
                        {
                            id = 3754,
                            account_number = "3879438912",
                            bank_name = "ABN AMRO CORPORATE FINANCE LIMITED",
                            routing_number = "620738095",
                            swift_bic = "BOFAGB22XXX",
                            uid = "add2b0ee-efff-46ba-9343-d6d725cff1e1"
                        },
                        new
                        {
                            id = 2967,
                            account_number = "4951420626",
                            bank_name = "ABG SUNDAL COLLIER LIMITED",
                            routing_number = "086797191",
                            swift_bic = "BARBGB2LLEI",
                            uid = "d714149c-ac07-4cbc-8964-d77825e0b364"
                        },
                        new
                        {
                            id = 5286,
                            account_number = "7399111702",
                            bank_name = "THE ROYAL BANK OF SCOTLAND PLC (FORMER RBS NV)",
                            routing_number = "106164222",
                            swift_bic = "BARBGB2LTOO",
                            uid = "59f30812-98fa-4e0d-ba73-34bcf3dde129"
                        },
                        new
                        {
                            id = 3817,
                            account_number = "2038434614",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "065069549",
                            swift_bic = "BOFAGB22XXX",
                            uid = "60ec56e9-52bd-4e67-87d3-23d3238af9be"
                        },
                        new
                        {
                            id = 2436,
                            account_number = "5779014630",
                            bank_name = "ABN AMRO HOARE GOVETT CORPORATE FINANCE LTD.",
                            routing_number = "000318307",
                            swift_bic = "BOFAGB22OF2",
                            uid = "d04a5452-75ca-4db5-b4f5-61e32bd4831a"
                        },
                        new
                        {
                            id = 8115,
                            account_number = "6510167356",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "046023481",
                            swift_bic = "BOFAGB4TLTR",
                            uid = "ad61c979-54be-4d6c-a02d-747c9bab25ad"
                        },
                        new
                        {
                            id = 7699,
                            account_number = "8977235708",
                            bank_name = "ABN AMRO CORPORATE FINANCE LIMITED",
                            routing_number = "804538943",
                            swift_bic = "BCYPGB2LMBB",
                            uid = "ac580346-0a21-4ca8-a235-958dbbce9067"
                        },
                        new
                        {
                            id = 5523,
                            account_number = "4406897234",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "035827342",
                            swift_bic = "BSABGB2LXXX",
                            uid = "a9a916fe-4ae1-4d27-a9e3-1dcdfe47be24"
                        },
                        new
                        {
                            id = 22,
                            account_number = "2340696804",
                            bank_name = "ABG SUNDAL COLLIER LIMITED",
                            routing_number = "641297955",
                            swift_bic = "AAPUGB21",
                            uid = "ffad1a6f-36b8-4e9c-bc8a-200a5c83a564"
                        },
                        new
                        {
                            id = 3620,
                            account_number = "5069122959",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "679460356",
                            swift_bic = "AAHVGB21",
                            uid = "c164abda-b240-4809-84bf-0f4ac370717b"
                        },
                        new
                        {
                            id = 9800,
                            account_number = "6424979116",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "057854102",
                            swift_bic = "BCYPGB2LCSB",
                            uid = "af305073-a2dc-4127-b71d-151ed845f4af"
                        },
                        new
                        {
                            id = 7910,
                            account_number = "5231057700",
                            bank_name = "ALLIED BANK PHILIPPINES (UK) PLC",
                            routing_number = "261579927",
                            swift_bic = "UBKLGB2LXXX",
                            uid = "8777933e-b884-48f7-a78f-27da6d812b04"
                        },
                        new
                        {
                            id = 3898,
                            account_number = "9811444763",
                            bank_name = "OTKRITIE SECURITIES LIMITED",
                            routing_number = "698458996",
                            swift_bic = "AANLGB2L",
                            uid = "85061ea1-90de-4c2c-a3b0-78ac96a6a340"
                        },
                        new
                        {
                            id = 763,
                            account_number = "6361141667",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "646281924",
                            swift_bic = "ABBYGB2L",
                            uid = "03a357be-c9b0-4e2c-a8c1-304f9412f309"
                        },
                        new
                        {
                            id = 3530,
                            account_number = "6690776043",
                            bank_name = "UBS CLEARING AND EXECUTION SERVICES LIMITED",
                            routing_number = "803976865",
                            swift_bic = "ANTSGB2LXXX",
                            uid = "96019b2a-a382-4a71-a120-4ba8b2476df3"
                        },
                        new
                        {
                            id = 9395,
                            account_number = "8996614354",
                            bank_name = "SANTANDER UK PLC",
                            routing_number = "106358737",
                            swift_bic = "AANLGB2L",
                            uid = "12359219-6fbf-4b54-bbcd-e4a788d63cd3"
                        },
                        new
                        {
                            id = 3785,
                            account_number = "2861612843",
                            bank_name = "ABN AMRO HOARE GOVETT CORPORATE FINANCE LTD.",
                            routing_number = "076809507",
                            swift_bic = "BOFAGB4TLTR",
                            uid = "b9865057-8e05-48a0-b68a-bc66fcce2e85"
                        },
                        new
                        {
                            id = 1604,
                            account_number = "4677665145",
                            bank_name = "ABC INTERNATIONAL BANK PLC",
                            routing_number = "697745244",
                            swift_bic = "BCYPGB2LHGB",
                            uid = "615d7645-3f65-4f24-aa5c-d6d88892dc84"
                        },
                        new
                        {
                            id = 4456,
                            account_number = "2718513403",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "640532925",
                            swift_bic = "BCYPGB2LCBB",
                            uid = "6ec7e2b7-2659-4c58-a459-3c657ef5d9de"
                        },
                        new
                        {
                            id = 1643,
                            account_number = "4808313284",
                            bank_name = "ABC INTERNATIONAL BANK PLC",
                            routing_number = "250876149",
                            swift_bic = "BARBGB2LKIL",
                            uid = "514642b3-75b0-4261-b243-e8e2635e1173"
                        },
                        new
                        {
                            id = 3061,
                            account_number = "9738656138",
                            bank_name = "ABU DHABI ISLAMIC BANK",
                            routing_number = "064120159",
                            swift_bic = "BOFAGB3SSWI",
                            uid = "d67945af-b2fa-4018-b9f1-c0e3d4094cf1"
                        },
                        new
                        {
                            id = 4954,
                            account_number = "5041705789",
                            bank_name = "ABINGWORTH MANAGEMENT LIMITED",
                            routing_number = "803005134",
                            swift_bic = "AAHVGB21",
                            uid = "a36b5787-2393-48ff-89d7-28542781bbfa"
                        },
                        new
                        {
                            id = 4148,
                            account_number = "9473112765",
                            bank_name = "ALLIED BANK PHILIPPINES (UK) PLC",
                            routing_number = "040207766",
                            swift_bic = "BOFAGB22OF2",
                            uid = "fe0e65f3-e5a6-42d0-9c74-c1f75212d14e"
                        },
                        new
                        {
                            id = 4346,
                            account_number = "5664996531",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "035114770",
                            swift_bic = "BOFAGB4TLFS",
                            uid = "aa693007-0b2d-4f19-b2d4-f0f8ca1a3eb7"
                        },
                        new
                        {
                            id = 9083,
                            account_number = "2439906081",
                            bank_name = "ABN AMRO FUND MANAGERS LIMITED",
                            routing_number = "276618530",
                            swift_bic = "AKBKGB22XXX",
                            uid = "7161361f-b782-4102-ae3e-c438bf37d202"
                        },
                        new
                        {
                            id = 3055,
                            account_number = "3233094230",
                            bank_name = "ALLIED BANK PHILIPPINES (UK) PLC",
                            routing_number = "674502222",
                            swift_bic = "BRBAGB2LXXX",
                            uid = "ed943ee2-5d68-49a4-933b-d18f18d4bb0d"
                        },
                        new
                        {
                            id = 6726,
                            account_number = "9874041672",
                            bank_name = "ABN AMRO CORPORATE FINANCE LIMITED",
                            routing_number = "807532580",
                            swift_bic = "BCYPGB2LHGB",
                            uid = "5f762587-1568-41eb-be26-82ac4e9a7ff8"
                        },
                        new
                        {
                            id = 1091,
                            account_number = "0753818055",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "110352761",
                            swift_bic = "ABCEGB2L",
                            uid = "91b871c8-3d99-47f0-ab6c-fb0c82e210aa"
                        },
                        new
                        {
                            id = 1712,
                            account_number = "5048566035",
                            bank_name = "ABINGWORTH MANAGEMENT LIMITED",
                            routing_number = "077002235",
                            swift_bic = "AAHOGB21",
                            uid = "4311f707-5aa3-45d3-aaeb-e7f964265cff"
                        },
                        new
                        {
                            id = 8461,
                            account_number = "2886802242",
                            bank_name = "THE ROYAL BANK OF SCOTLAND PLC (FORMER RBS NV)",
                            routing_number = "263975024",
                            swift_bic = "AANLGB2L",
                            uid = "e00bbe8e-9d53-4f19-bf10-e8ab8d2ed201"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
