// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prueba_tecnica_finixgroup.Helpers;

#nullable disable

namespace prueba_tecnica_finixgroup.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240313051521_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("prueba_tecnica_finixgroup.Server.Models.Bank", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IBAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("account_number")
                        .HasColumnType("TEXT");

                    b.Property<string>("bank_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("routing_number")
                        .HasColumnType("TEXT");

                    b.Property<string>("swift_bic")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("uid")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            id = 2946,
                            account_number = "2175186024",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "307473835",
                            swift_bic = "AAPUGB21",
                            uid = new Guid("3cf2f166-19b4-4ffe-bab9-bf5bc3f4fa64")
                        },
                        new
                        {
                            id = 3331,
                            account_number = "9062579305",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "677372967",
                            swift_bic = "BCYPGB2LCBB",
                            uid = new Guid("616bcd45-d64c-415e-8520-7c8a016a2092")
                        },
                        new
                        {
                            id = 5177,
                            account_number = "8203501267",
                            bank_name = "ABN AMRO HOARE GOVETT CORPORATE FINANCE LTD.",
                            routing_number = "725393911",
                            swift_bic = "ABCEGB2L",
                            uid = new Guid("c5709546-046d-4bb3-a0c9-7a8394ae0711")
                        },
                        new
                        {
                            id = 2975,
                            account_number = "2463636609",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "099099679",
                            swift_bic = "BOFAGB4TCDO",
                            uid = new Guid("8c5ccac2-f47b-4783-b6c7-662cb1d46b1f")
                        },
                        new
                        {
                            id = 2540,
                            account_number = "7036346156",
                            bank_name = "ABC INTERNATIONAL BANK PLC",
                            routing_number = "320174250",
                            swift_bic = "BOFAGB4TIPA",
                            uid = new Guid("f26d51ee-1d2c-4e3c-a731-0c8d851025b0")
                        },
                        new
                        {
                            id = 7089,
                            account_number = "3984496637",
                            bank_name = "UBS CLEARING AND EXECUTION SERVICES LIMITED",
                            routing_number = "723798217",
                            swift_bic = "ABFIGB21",
                            uid = new Guid("5527b36d-ca2f-46dd-900c-fbc83c60e296")
                        },
                        new
                        {
                            id = 1044,
                            account_number = "6655882521",
                            bank_name = "ABN AMRO HOARE GOVETT CORPORATE FINANCE LTD.",
                            routing_number = "656597585",
                            swift_bic = "BARBGB2LTOO",
                            uid = new Guid("8e312a88-6875-4e43-979a-5ba9fa9eb479")
                        },
                        new
                        {
                            id = 8650,
                            account_number = "0722483217",
                            bank_name = "UBS CLEARING AND EXECUTION SERVICES LIMITED",
                            routing_number = "031229300",
                            swift_bic = "BCYPGB2LBBB",
                            uid = new Guid("b33d7d04-1985-442d-85c2-a6ae987e67b6")
                        },
                        new
                        {
                            id = 6576,
                            account_number = "7733616268",
                            bank_name = "UBS CLEARING AND EXECUTION SERVICES LIMITED",
                            routing_number = "280428787",
                            swift_bic = "BCYPGB2LSSB",
                            uid = new Guid("202e5533-4c36-4044-b89b-439fdd726827")
                        },
                        new
                        {
                            id = 5702,
                            account_number = "1677311862",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "305958404",
                            swift_bic = "BCYPGB2LPGB",
                            uid = new Guid("6cde92e2-c03f-49c7-b865-7f0760a0eb45")
                        },
                        new
                        {
                            id = 1946,
                            account_number = "5817841485",
                            bank_name = "PGMS (GLASGOW) LIMITED",
                            routing_number = "655558130",
                            swift_bic = "BOFAGB22CLS",
                            uid = new Guid("bc055217-570e-47b9-b411-90d0daf0384a")
                        },
                        new
                        {
                            id = 2306,
                            account_number = "0662038705",
                            bank_name = "ABU DHABI ISLAMIC BANK",
                            routing_number = "800639189",
                            swift_bic = "ABNAGB21VOC",
                            uid = new Guid("2a22904f-1975-404d-a229-dd44125a41ba")
                        },
                        new
                        {
                            id = 1293,
                            account_number = "0732132424",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "213559115",
                            swift_bic = "UBKLGB2LXXX",
                            uid = new Guid("5feaab1c-8a0c-4ff8-8d5c-0f42164a3a8f")
                        },
                        new
                        {
                            id = 9528,
                            account_number = "8519919354",
                            bank_name = "ALLIED BANK PHILIPPINES (UK) PLC",
                            routing_number = "619925660",
                            swift_bic = "BARBGB2LKEN",
                            uid = new Guid("a4e16c1c-c509-4ebd-b807-3ff8b95b3262")
                        },
                        new
                        {
                            id = 2593,
                            account_number = "1099565609",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "613390084",
                            swift_bic = "ALEIGB22TSY",
                            uid = new Guid("41c340f4-782e-45fe-9ca3-f1b1aaf4229b")
                        },
                        new
                        {
                            id = 1684,
                            account_number = "4824836895",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "661169377",
                            swift_bic = "BARBGB2LBIR",
                            uid = new Guid("e5da122c-a752-43bb-9022-0c1f9ec52a11")
                        },
                        new
                        {
                            id = 4271,
                            account_number = "9226259614",
                            bank_name = "AAC CAPITAL PARTNERS LIMITED",
                            routing_number = "315214549",
                            swift_bic = "AAFMGB21",
                            uid = new Guid("ad2b4ef3-22cf-488c-8f14-b37cddfcf545")
                        },
                        new
                        {
                            id = 9709,
                            account_number = "7683878143",
                            bank_name = "ABN AMRO CORPORATE FINANCE LIMITED",
                            routing_number = "260023429",
                            swift_bic = "AANLGB2L",
                            uid = new Guid("0ed9bb84-7c3b-44e4-922a-68b1278edbc2")
                        },
                        new
                        {
                            id = 2505,
                            account_number = "5685927950",
                            bank_name = "ABN AMRO CORPORATE FINANCE LIMITED",
                            routing_number = "808230014",
                            swift_bic = "ASTPGB2LXXX",
                            uid = new Guid("b5610193-37fc-4586-983f-044ddfc196cb")
                        },
                        new
                        {
                            id = 5616,
                            account_number = "4750231753",
                            bank_name = "ABBEY LIFE",
                            routing_number = "115000212",
                            swift_bic = "UBKLGB2LBAK",
                            uid = new Guid("88c2547b-ffd4-4a4b-ba31-e4cdcddfd239")
                        },
                        new
                        {
                            id = 4309,
                            account_number = "7229890277",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "302500965",
                            swift_bic = "BOFAGB22OF2",
                            uid = new Guid("e6298731-bd6f-4289-9d8c-8dbb2c0d73a7")
                        },
                        new
                        {
                            id = 1760,
                            account_number = "9095140009",
                            bank_name = "THE ROYAL BANK OF SCOTLAND PLC (FORMER RBS NV)",
                            routing_number = "230376423",
                            swift_bic = "ABECGB21",
                            uid = new Guid("023ae084-7ea0-4dde-9f30-a4513171325c")
                        },
                        new
                        {
                            id = 5924,
                            account_number = "1628405193",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "721579784",
                            swift_bic = "ABNAGB21VOC",
                            uid = new Guid("1dd227d0-9096-4bfd-ae87-08f15a3486b8")
                        },
                        new
                        {
                            id = 8499,
                            account_number = "4452236206",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "087924581",
                            swift_bic = "BCYPGB2LHHB",
                            uid = new Guid("aa97b56e-518c-4837-abbf-454f3176c1d2")
                        },
                        new
                        {
                            id = 3735,
                            account_number = "3464171977",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "087529737",
                            swift_bic = "ANTSGB2LCHA",
                            uid = new Guid("5c4d5ef8-f44f-479a-aa1f-9af3ed0f9c58")
                        },
                        new
                        {
                            id = 2729,
                            account_number = "7671772840",
                            bank_name = "ABN AMRO HOARE GOVETT SECURITIES",
                            routing_number = "637518693",
                            swift_bic = "BOFAGB22SEC",
                            uid = new Guid("095d9a71-fef5-401c-876a-dd4d6ff52ffc")
                        },
                        new
                        {
                            id = 6614,
                            account_number = "9338417038",
                            bank_name = "ABN AMRO CORPORATE FINANCE LIMITED",
                            routing_number = "284413921",
                            swift_bic = "BOFAGB4TLFS",
                            uid = new Guid("63fca0d9-44cc-475b-abc9-eb205bf0f503")
                        },
                        new
                        {
                            id = 7946,
                            account_number = "5221183878",
                            bank_name = "AAC CAPITAL PARTNERS LIMITED",
                            routing_number = "266635015",
                            swift_bic = "AAPUGB21",
                            uid = new Guid("5d31322b-dc0f-4f1e-b943-1ed5e87f680f")
                        },
                        new
                        {
                            id = 5410,
                            account_number = "9498037270",
                            bank_name = "AAC CAPITAL PARTNERS LIMITED",
                            routing_number = "642524407",
                            swift_bic = "BSABGB2LXXX",
                            uid = new Guid("d6ab2d75-d132-4a7b-91c1-b8a6f05aaf83")
                        },
                        new
                        {
                            id = 7011,
                            account_number = "3759084489",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "807664186",
                            swift_bic = "AAFMGB21",
                            uid = new Guid("9a6a8302-e6ec-4ac8-824e-d0902c0e54fe")
                        },
                        new
                        {
                            id = 1384,
                            account_number = "9920208729",
                            bank_name = "THE ROYAL BANK OF SCOTLAND PLC (FORMER RBS NV)",
                            routing_number = "690322703",
                            swift_bic = "AKBKGB22XXX",
                            uid = new Guid("f2b3e060-060f-4a8d-a453-d4f4d3a0faa9")
                        },
                        new
                        {
                            id = 7081,
                            account_number = "4514427067",
                            bank_name = "ABN AMRO HOARE GOVETT LIMITED",
                            routing_number = "629265446",
                            swift_bic = "BOFAGB22SCP",
                            uid = new Guid("cb1becf1-82e7-485c-b63e-be36202c9ba8")
                        },
                        new
                        {
                            id = 7793,
                            account_number = "9754118202",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "314834917",
                            swift_bic = "UBKLGB2LBAK",
                            uid = new Guid("435adc76-08b9-4166-81bf-58e8c907b7d1")
                        },
                        new
                        {
                            id = 3897,
                            account_number = "8030446400",
                            bank_name = "ABC INTERNATIONAL BANK PLC",
                            routing_number = "682672348",
                            swift_bic = "AACCGB21",
                            uid = new Guid("5153c207-ff0c-4cb1-b1e2-7e38ed607d5a")
                        },
                        new
                        {
                            id = 9514,
                            account_number = "0909666287",
                            bank_name = "AAC CAPITAL PARTNERS LIMITED",
                            routing_number = "282347879",
                            swift_bic = "BARBGB2LKEN",
                            uid = new Guid("4e8cbf9f-555f-4d9c-8952-6a71b13bf51a")
                        },
                        new
                        {
                            id = 1839,
                            account_number = "0578657349",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "263456611",
                            swift_bic = "UBKLGB2LXXX",
                            uid = new Guid("2063985c-ffc8-4b60-a872-a18e7681cf91")
                        },
                        new
                        {
                            id = 2256,
                            account_number = "8306921376",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "688226646",
                            swift_bic = "BCYPGB2LMBB",
                            uid = new Guid("0f05e2f4-9127-490b-a868-bf7319a9e2a1")
                        },
                        new
                        {
                            id = 3996,
                            account_number = "5734840945",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "269741142",
                            swift_bic = "ABBYGB2L",
                            uid = new Guid("c7abe6e1-0c3e-4243-adcc-d792b41d4bc2")
                        },
                        new
                        {
                            id = 9886,
                            account_number = "9024294320",
                            bank_name = "ABG SUNDAL COLLIER LIMITED",
                            routing_number = "217927031",
                            swift_bic = "BCYPGB2LMBB",
                            uid = new Guid("66418a05-5f55-4bc6-82d0-724a35aeef5f")
                        },
                        new
                        {
                            id = 6966,
                            account_number = "9581210759",
                            bank_name = "ABN AMRO FUND MANAGERS LIMITED",
                            routing_number = "642669304",
                            swift_bic = "ABCEGB2L",
                            uid = new Guid("fa634263-569d-48f2-a964-6355368d9bdd")
                        },
                        new
                        {
                            id = 4862,
                            account_number = "6256633427",
                            bank_name = "ABN AMRO CORPORATE FINANCE LIMITED",
                            routing_number = "677596837",
                            swift_bic = "UBKLGB2LXXX",
                            uid = new Guid("ed3770a3-9281-4c19-b521-7d267d508b39")
                        },
                        new
                        {
                            id = 8828,
                            account_number = "9908684348",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "028528373",
                            swift_bic = "BSABGB2LXXX",
                            uid = new Guid("451ad112-a681-485f-b92e-7db7c33e66bc")
                        },
                        new
                        {
                            id = 5402,
                            account_number = "2259922501",
                            bank_name = "AAC CAPITAL PARTNERS LIMITED",
                            routing_number = "051693233",
                            swift_bic = "ANTSGB2LCHA",
                            uid = new Guid("c1e7a6bf-6ce5-4ea2-bac6-1cc145340e2a")
                        },
                        new
                        {
                            id = 8130,
                            account_number = "7192086499",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "708283679",
                            swift_bic = "BSABGB2LXXX",
                            uid = new Guid("fcc5f6cd-c930-4924-949a-b35038ddd2be")
                        },
                        new
                        {
                            id = 639,
                            account_number = "0527202304",
                            bank_name = "ABN AMRO HOARE GOVETT LIMITED",
                            routing_number = "613832458",
                            swift_bic = "BARBGB2LBIR",
                            uid = new Guid("523367c0-fcb5-424a-bc43-16f8f919d48f")
                        },
                        new
                        {
                            id = 2547,
                            account_number = "1044565900",
                            bank_name = "ABINGWORTH MANAGEMENT LIMITED",
                            routing_number = "706139123",
                            swift_bic = "ABECGB21",
                            uid = new Guid("2f6887d9-5dfd-41c0-a6e8-9620e9e087c4")
                        },
                        new
                        {
                            id = 9216,
                            account_number = "9415825639",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "001160936",
                            swift_bic = "BKCHGB2LXXX",
                            uid = new Guid("5a79448a-82c4-44df-9fe0-78dfe7f1cdce")
                        },
                        new
                        {
                            id = 4975,
                            account_number = "1705669071",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "005031870",
                            swift_bic = "BSABGB2LXXX",
                            uid = new Guid("a54bd811-3473-47a4-a1d6-694228612f0d")
                        },
                        new
                        {
                            id = 7845,
                            account_number = "5361107242",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "055093114",
                            swift_bic = "BARBGB2LMAN",
                            uid = new Guid("51b321c1-678b-4c84-a803-aa4b6541a214")
                        },
                        new
                        {
                            id = 5265,
                            account_number = "8528246590",
                            bank_name = "ABN AMRO HOARE GOVETT SECURITIES",
                            routing_number = "228396415",
                            swift_bic = "BCYPGB2LCSB",
                            uid = new Guid("3bc33768-568d-4078-9c6a-f7bb21697f95")
                        },
                        new
                        {
                            id = 557,
                            account_number = "4453330102",
                            bank_name = "ABN AMRO CORPORATE FINANCE LIMITED",
                            routing_number = "095734116",
                            swift_bic = "BSCHGB2LEQU",
                            uid = new Guid("8fcf7df6-a810-4cea-8189-6a06773d3458")
                        },
                        new
                        {
                            id = 3629,
                            account_number = "8331595411",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "081857968",
                            swift_bic = "ABECGB21",
                            uid = new Guid("d26adc51-e9a2-4e48-aee9-5072e136193d")
                        },
                        new
                        {
                            id = 7159,
                            account_number = "7125664297",
                            bank_name = "ABG SUNDAL COLLIER LIMITED",
                            routing_number = "115409664",
                            swift_bic = "BKCHGB2LXXX",
                            uid = new Guid("df958dab-88c3-4d28-aebf-65236b08c96a")
                        },
                        new
                        {
                            id = 1792,
                            account_number = "4910392711",
                            bank_name = "THE ROYAL BANK OF SCOTLAND PLC (FORMER RBS NV)",
                            routing_number = "111710917",
                            swift_bic = "ANTSGB2LCHA",
                            uid = new Guid("6ca24e05-533f-49f4-ad41-aa4ca5b2e4c9")
                        },
                        new
                        {
                            id = 95,
                            account_number = "6294614778",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "027200760",
                            swift_bic = "BARBGB2LKEN",
                            uid = new Guid("8cc0a47d-1ef6-40ff-8bf0-b6689aea7651")
                        },
                        new
                        {
                            id = 3730,
                            account_number = "1859425221",
                            bank_name = "ALLIED BANK PHILIPPINES (UK) PLC",
                            routing_number = "238246351",
                            swift_bic = "BCYPGB2LCSB",
                            uid = new Guid("e997e0fe-a72a-44bc-a8fa-64cbddc19e8c")
                        },
                        new
                        {
                            id = 1294,
                            account_number = "1000747406",
                            bank_name = "ALLIED BANK PHILIPPINES (UK) PLC",
                            routing_number = "019076944",
                            swift_bic = "ABAZGB21",
                            uid = new Guid("96220942-2eb0-4646-9082-8763b86cf6ee")
                        },
                        new
                        {
                            id = 2646,
                            account_number = "2327123106",
                            bank_name = "ABG SUNDAL COLLIER LIMITED",
                            routing_number = "662418506",
                            swift_bic = "BRBAGB2LXXX",
                            uid = new Guid("7af616f1-3797-44ba-ad3a-a2e51a3b2f40")
                        },
                        new
                        {
                            id = 2437,
                            account_number = "4395070320",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "050575255",
                            swift_bic = "AKBKGB22XXX",
                            uid = new Guid("239c184c-cca3-4303-a641-7c3b838d2014")
                        },
                        new
                        {
                            id = 5326,
                            account_number = "1157408826",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "007996845",
                            swift_bic = "BOFAGB22SCP",
                            uid = new Guid("57482c7c-a8c5-4d2a-a92c-8c53f218b1a9")
                        },
                        new
                        {
                            id = 9512,
                            account_number = "4064094308",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "082601346",
                            swift_bic = "AACNGB21",
                            uid = new Guid("2ecbfc9f-e177-4aee-916b-fe75264d811a")
                        },
                        new
                        {
                            id = 9759,
                            account_number = "1998013515",
                            bank_name = "AAC CAPITAL PARTNERS LIMITED",
                            routing_number = "051607847",
                            swift_bic = "ANTSGB2LCHA",
                            uid = new Guid("d735a9f5-9ab5-412e-bd84-ae659915b7c5")
                        },
                        new
                        {
                            id = 6940,
                            account_number = "4191400435",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "257006527",
                            swift_bic = "AANLGB2L",
                            uid = new Guid("cd1a2c4f-bb34-4d4b-8a34-5a429b8b7274")
                        },
                        new
                        {
                            id = 7643,
                            account_number = "6579813345",
                            bank_name = "ABN AMRO HOARE GOVETT LIMITED",
                            routing_number = "241366781",
                            swift_bic = "BOFAGB4TLTR",
                            uid = new Guid("c685cc36-43cd-4881-91ae-bbeb718da3cb")
                        },
                        new
                        {
                            id = 9226,
                            account_number = "0769351163",
                            bank_name = "ABN AMRO HOARE GOVETT CORPORATE FINANCE LTD.",
                            routing_number = "678582439",
                            swift_bic = "BOFAGB4TLFS",
                            uid = new Guid("3fe5352a-1084-4760-89e9-c514cc3d7c16")
                        },
                        new
                        {
                            id = 6230,
                            account_number = "1475069159",
                            bank_name = "AAC CAPITAL PARTNERS LIMITED",
                            routing_number = "621204793",
                            swift_bic = "UBKLGB2LXXX",
                            uid = new Guid("3ddef91f-4e8d-40a9-9c69-daff86b6e9aa")
                        },
                        new
                        {
                            id = 9118,
                            account_number = "2681812229",
                            bank_name = "ABN AMRO HOARE GOVETT SECURITIES",
                            routing_number = "019085304",
                            swift_bic = "ANTSGB2LCHA",
                            uid = new Guid("23da80f6-2c6a-4d5b-b4a3-34d8056154c2")
                        },
                        new
                        {
                            id = 7613,
                            account_number = "5038086178",
                            bank_name = "ABG SUNDAL COLLIER LIMITED",
                            routing_number = "268561844",
                            swift_bic = "BRBAGB2LXXX",
                            uid = new Guid("ef57993b-899a-4283-b5fd-cd89469a3430")
                        },
                        new
                        {
                            id = 3351,
                            account_number = "0358369447",
                            bank_name = "ABN AMRO FUND MANAGERS LIMITED",
                            routing_number = "681060760",
                            swift_bic = "BCYPGB2LXXX",
                            uid = new Guid("d47dd363-8f32-4315-8f96-e2060d78f0dc")
                        },
                        new
                        {
                            id = 5262,
                            account_number = "4437955817",
                            bank_name = "ABBEY LIFE",
                            routing_number = "046206321",
                            swift_bic = "ANTSGB2LXXX",
                            uid = new Guid("0b9a62ea-d523-49b9-b800-a9b52dd64914")
                        },
                        new
                        {
                            id = 2006,
                            account_number = "3770488109",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "670089286",
                            swift_bic = "BCYPGB2LCSB",
                            uid = new Guid("658a50f7-5dac-45df-b228-a04dc94a9943")
                        },
                        new
                        {
                            id = 1843,
                            account_number = "7631586084",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "312027904",
                            swift_bic = "UBKLGB2LXXX",
                            uid = new Guid("cfe0502f-7d72-4ff1-96af-baf5f814ed01")
                        },
                        new
                        {
                            id = 7028,
                            account_number = "7653217065",
                            bank_name = "PGMS (GLASGOW) LIMITED",
                            routing_number = "060096261",
                            swift_bic = "BARBGB2LKEN",
                            uid = new Guid("81ea1e59-eb33-4684-a322-1b50222c61bf")
                        },
                        new
                        {
                            id = 5435,
                            account_number = "7813923604",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "263232356",
                            swift_bic = "BOFAGB4TCCD",
                            uid = new Guid("0812526d-3f9f-41a8-9a15-0464938beebd")
                        },
                        new
                        {
                            id = 4659,
                            account_number = "1895677287",
                            bank_name = "AAC CAPITAL PARTNERS LIMITED",
                            routing_number = "805097658",
                            swift_bic = "ABCMGB21",
                            uid = new Guid("9c755920-0f13-4e73-a7f6-127daa0e2b05")
                        },
                        new
                        {
                            id = 5679,
                            account_number = "9356610914",
                            bank_name = "UBS CLEARING AND EXECUTION SERVICES LIMITED",
                            routing_number = "683856419",
                            swift_bic = "AAPUGB21",
                            uid = new Guid("b1a3dcd1-b169-4392-babb-0c4af503c2d5")
                        },
                        new
                        {
                            id = 2238,
                            account_number = "7289778048",
                            bank_name = "THE ROYAL BANK OF SCOTLAND PLC (FORMER RBS NV)",
                            routing_number = "682667719",
                            swift_bic = "ANTSGB2LXXX",
                            uid = new Guid("3e742568-8d05-48e9-abc9-88e02dd74300")
                        },
                        new
                        {
                            id = 4312,
                            account_number = "3609513352",
                            bank_name = "ABBOTSTONE AGRICULTURAL PROPERTY UNIT TRUST",
                            routing_number = "087438420",
                            swift_bic = "BCYPGB2LHGB",
                            uid = new Guid("969838ff-2e1d-48bb-b7b3-cd014997dfcc")
                        },
                        new
                        {
                            id = 1794,
                            account_number = "7153500295",
                            bank_name = "THE ROYAL BANK OF SCOTLAND PLC (FORMER RBS NV)",
                            routing_number = "015089126",
                            swift_bic = "BARBGB2LSOU",
                            uid = new Guid("a2ff3881-b63a-4936-bb3e-4d400ef8d5da")
                        },
                        new
                        {
                            id = 3170,
                            account_number = "5831043677",
                            bank_name = "ABN AMRO MEZZANINE (UK) LIMITED",
                            routing_number = "654479090",
                            swift_bic = "BOFAGB22SEC",
                            uid = new Guid("918bd8f5-1143-468c-8f95-41c5b7b4bb64")
                        },
                        new
                        {
                            id = 4663,
                            account_number = "4382482909",
                            bank_name = "ALLIED BANK PHILIPPINES (UK) PLC",
                            routing_number = "613793270",
                            swift_bic = "ABCMGB21",
                            uid = new Guid("3126cb6a-1642-4dea-a582-5f19e365857a")
                        },
                        new
                        {
                            id = 6782,
                            account_number = "4864943626",
                            bank_name = "ABN AMRO HOARE GOVETT CORPORATE FINANCE LTD.",
                            routing_number = "033154907",
                            swift_bic = "AIBKGB2XTSY",
                            uid = new Guid("8eab14da-e0e5-45eb-a2b6-259a15cb8e42")
                        },
                        new
                        {
                            id = 3754,
                            account_number = "9789754046",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "614772012",
                            swift_bic = "BARBGB2LHAR",
                            uid = new Guid("03ba9b37-e0d7-4201-92e2-2f7829ff6fde")
                        },
                        new
                        {
                            id = 8995,
                            account_number = "5957424831",
                            bank_name = "OTKRITIE SECURITIES LIMITED",
                            routing_number = "326236749",
                            swift_bic = "ABBYGB2L",
                            uid = new Guid("14c0be48-c9b9-4a42-8bbb-f5ac8728f561")
                        },
                        new
                        {
                            id = 4781,
                            account_number = "6474483826",
                            bank_name = "ABN AMRO HOARE GOVETT CORPORATE FINANCE LTD.",
                            routing_number = "004175902",
                            swift_bic = "BOFAGB4TLFS",
                            uid = new Guid("ba669989-67d5-4aae-a66d-01df91fafa09")
                        },
                        new
                        {
                            id = 8709,
                            account_number = "5483486474",
                            bank_name = "ABN AMRO HOARE GOVETT CORPORATE FINANCE LTD.",
                            routing_number = "727991638",
                            swift_bic = "BOFAGB4TCDO",
                            uid = new Guid("09c5802f-80e5-492d-b90e-c423bb1342b5")
                        },
                        new
                        {
                            id = 545,
                            account_number = "3205585355",
                            bank_name = "ALLIED BANK PHILIPPINES (UK) PLC",
                            routing_number = "039468891",
                            swift_bic = "BOFAGB4TCDO",
                            uid = new Guid("f6227478-ff23-4e45-86d0-67dc5cbadcad")
                        },
                        new
                        {
                            id = 2111,
                            account_number = "9391171613",
                            bank_name = "ABINGWORTH MANAGEMENT LIMITED",
                            routing_number = "632253717",
                            swift_bic = "ABCEGB2L",
                            uid = new Guid("48ea6761-c9bc-4ee4-9dff-3f30ef25b716")
                        },
                        new
                        {
                            id = 6618,
                            account_number = "7336430907",
                            bank_name = "ABN AMRO QUOTED INVESTMENTS (UK) LIMITED",
                            routing_number = "630931743",
                            swift_bic = "AANLGB2L",
                            uid = new Guid("ccef4b43-cd27-4c07-beb3-02dcde9ab8a3")
                        },
                        new
                        {
                            id = 3583,
                            account_number = "8215043803",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "681933114",
                            swift_bic = "BARBGB2LTOO",
                            uid = new Guid("85a0c421-f342-46cf-b928-81e9172d6768")
                        },
                        new
                        {
                            id = 7429,
                            account_number = "9794272840",
                            bank_name = "PGMS (GLASGOW) LIMITED",
                            routing_number = "307002536",
                            swift_bic = "BCEYGB2LXXX",
                            uid = new Guid("2c3ef8cb-960e-41c2-b404-d5e1e5cb98a9")
                        },
                        new
                        {
                            id = 6256,
                            account_number = "9678903551",
                            bank_name = "UBS CLEARING AND EXECUTION SERVICES LIMITED",
                            routing_number = "098754630",
                            swift_bic = "BCYPGB2LHHB",
                            uid = new Guid("20422dab-1cb5-4799-92e7-5641d0d4ee48")
                        },
                        new
                        {
                            id = 6124,
                            account_number = "8736284876",
                            bank_name = "ABN AMRO CORPORATE FINANCE LIMITED",
                            routing_number = "285772687",
                            swift_bic = "BSABGB2LXXX",
                            uid = new Guid("5d8ff2b6-68b4-4221-ad87-c2434300c20b")
                        },
                        new
                        {
                            id = 9300,
                            account_number = "9329277815",
                            bank_name = "ABINGWORTH MANAGEMENT LIMITED",
                            routing_number = "068524353",
                            swift_bic = "BCYPGB2LMBB",
                            uid = new Guid("2d5ed98e-56e3-4d3d-b26e-ec3afd48df5b")
                        },
                        new
                        {
                            id = 2737,
                            account_number = "0586994297",
                            bank_name = "ALLIED BANK PHILIPPINES (UK) PLC",
                            routing_number = "276129689",
                            swift_bic = "BOFAGB22SEC",
                            uid = new Guid("05be1eb2-e6b6-48a1-8cb6-e64dd7e8591a")
                        },
                        new
                        {
                            id = 7959,
                            account_number = "3387364407",
                            bank_name = "ABN AMRO FUND MANAGERS LIMITED",
                            routing_number = "243069701",
                            swift_bic = "BOFAGB4TCCD",
                            uid = new Guid("1825b49c-2bcf-4e05-b10c-43c25cf78f32")
                        },
                        new
                        {
                            id = 7313,
                            account_number = "4749848658",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "807143131",
                            swift_bic = "BARBGB2LHAR",
                            uid = new Guid("864ff07b-10c0-4b63-a15e-4ac6e8cf4c16")
                        },
                        new
                        {
                            id = 985,
                            account_number = "5677377307",
                            bank_name = "ABG SUNDAL COLLIER LIMITED",
                            routing_number = "007645882",
                            swift_bic = "ABCMGB21",
                            uid = new Guid("44ef9aac-156f-413d-a317-dc67d8ebd50a")
                        },
                        new
                        {
                            id = 1926,
                            account_number = "0895321850",
                            bank_name = "THE ROYAL BANK OF SCOTLAND PLC (FORMER RBS NV)",
                            routing_number = "008179247",
                            swift_bic = "BRBAGB2LXXX",
                            uid = new Guid("efda52dd-6454-4c88-bf72-2a4fb16c97a3")
                        },
                        new
                        {
                            id = 7217,
                            account_number = "5566379053",
                            bank_name = "ALKEN ASSET MANAGEMENT",
                            routing_number = "102701647",
                            swift_bic = "ABDIGB21",
                            uid = new Guid("62856ce0-8582-4115-a0f9-406bc4b10881")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
